name: yacht_isar_generator
description: Yacht Isar Generator
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ">=4.6.0 <6.0.0"
  isar: ^3.0.5
  isar_generator: ^3.0.5
  yacht:
    path: ../yacht